# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(373, 467)
        MainWindow.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.push_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_8.sizePolicy().hasHeightForWidth())
        self.push_8.setSizePolicy(sizePolicy)
        self.push_8.setStyleSheet("QPushButton{\n"
"         \n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"  background-color: rgb(194, 255, 230);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              \n"
"    color: rgb(50, 50, 50);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(135, 161, 166);\n"
"\n"
"    color: rgb(131, 255, 241);\n"
"}")
        self.push_8.setObjectName("push_8")
        self.gridLayout_3.addWidget(self.push_8, 4, 1, 1, 1)
        self.push_equ = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_equ.sizePolicy().hasHeightForWidth())
        self.push_equ.setSizePolicy(sizePolicy)
        self.push_equ.setStyleSheet("QPushButton{\n"
"font: 75 28pt \"MS Shell Dlg 2\";\n"
"        color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 112);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              color: rgb(255, 152, 120);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 160, 160);\n"
"color: rgb(131, 255, 241);\n"
"}\n"
"")
        self.push_equ.setObjectName("push_equ")
        self.gridLayout_3.addWidget(self.push_equ, 5, 3, 1, 1)
        self.push_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_6.sizePolicy().hasHeightForWidth())
        self.push_6.setSizePolicy(sizePolicy)
        self.push_6.setStyleSheet("QPushButton{\n"
"         \n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"  background-color: rgb(194, 255, 230);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              \n"
"    color: rgb(50, 50, 50);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(135, 161, 166);\n"
"\n"
"    color: rgb(131, 255, 241);\n"
"}")
        self.push_6.setObjectName("push_6")
        self.gridLayout_3.addWidget(self.push_6, 3, 2, 1, 1)
        self.push_dot = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_dot.sizePolicy().hasHeightForWidth())
        self.push_dot.setSizePolicy(sizePolicy)
        self.push_dot.setStyleSheet("QPushButton{\n"
"         \n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"  background-color: rgb(194, 255, 230);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              \n"
"    color: rgb(50, 50, 50);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(135, 161, 166);\n"
"\n"
"    color: rgb(131, 255, 241);\n"
"}")
        self.push_dot.setObjectName("push_dot")
        self.gridLayout_3.addWidget(self.push_dot, 5, 2, 1, 1)
        self.push_div = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_div.sizePolicy().hasHeightForWidth())
        self.push_div.setSizePolicy(sizePolicy)
        self.push_div.setStyleSheet("QPushButton{\n"
"font: 75 28pt \"MS Shell Dlg 2\";\n"
"        color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 112);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              color: rgb(255, 152, 120);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 160, 160);\n"
"color: rgb(131, 255, 241);\n"
"}")
        self.push_div.setObjectName("push_div")
        self.gridLayout_3.addWidget(self.push_div, 4, 3, 1, 1)
        self.push_min = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_min.sizePolicy().hasHeightForWidth())
        self.push_min.setSizePolicy(sizePolicy)
        self.push_min.setStyleSheet("QPushButton{\n"
"font: 75 28pt \"MS Shell Dlg 2\";\n"
"        color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 112);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              color: rgb(255, 152, 120);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 160, 160);\n"
"color: rgb(131, 255, 241);\n"
"}")
        self.push_min.setObjectName("push_min")
        self.gridLayout_3.addWidget(self.push_min, 2, 3, 1, 1)
        self.push_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_4.sizePolicy().hasHeightForWidth())
        self.push_4.setSizePolicy(sizePolicy)
        self.push_4.setStyleSheet("QPushButton{\n"
"         \n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"  background-color: rgb(194, 255, 230);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              \n"
"    color: rgb(50, 50, 50);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(135, 161, 166);\n"
"\n"
"    color: rgb(131, 255, 241);\n"
"}")
        self.push_4.setObjectName("push_4")
        self.gridLayout_3.addWidget(self.push_4, 3, 0, 1, 1)
        self.push_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_7.sizePolicy().hasHeightForWidth())
        self.push_7.setSizePolicy(sizePolicy)
        self.push_7.setStyleSheet("QPushButton{\n"
"         \n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"  background-color: rgb(194, 255, 230);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              \n"
"    color: rgb(50, 50, 50);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(135, 161, 166);\n"
"\n"
"    color: rgb(131, 255, 241);\n"
"}")
        self.push_7.setObjectName("push_7")
        self.gridLayout_3.addWidget(self.push_7, 4, 0, 1, 1)
        self.push_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_9.sizePolicy().hasHeightForWidth())
        self.push_9.setSizePolicy(sizePolicy)
        self.push_9.setStyleSheet("QPushButton{\n"
"         \n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"  background-color: rgb(194, 255, 230);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              \n"
"    color: rgb(50, 50, 50);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(135, 161, 166);\n"
"\n"
"    color: rgb(131, 255, 241);\n"
"}")
        self.push_9.setObjectName("push_9")
        self.gridLayout_3.addWidget(self.push_9, 4, 2, 1, 1)
        self.push_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_1.sizePolicy().hasHeightForWidth())
        self.push_1.setSizePolicy(sizePolicy)
        self.push_1.setStyleSheet("QPushButton{\n"
"         \n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"  background-color: rgb(194, 255, 230);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              \n"
"    color: rgb(50, 50, 50);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(135, 161, 166);\n"
"\n"
"    color: rgb(131, 255, 241);\n"
"}")
        self.push_1.setObjectName("push_1")
        self.gridLayout_3.addWidget(self.push_1, 2, 0, 1, 1)
        self.push_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_3.sizePolicy().hasHeightForWidth())
        self.push_3.setSizePolicy(sizePolicy)
        self.push_3.setStyleSheet("QPushButton{\n"
"         \n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"  background-color: rgb(194, 255, 230);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              \n"
"    color: rgb(50, 50, 50);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(135, 161, 166);\n"
"\n"
"    color: rgb(131, 255, 241);\n"
"}")
        self.push_3.setObjectName("push_3")
        self.gridLayout_3.addWidget(self.push_3, 2, 2, 1, 1)
        self.push_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_5.sizePolicy().hasHeightForWidth())
        self.push_5.setSizePolicy(sizePolicy)
        self.push_5.setStyleSheet("QPushButton{\n"
"         \n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"  background-color: rgb(194, 255, 230);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              \n"
"    color: rgb(50, 50, 50);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(135, 161, 166);\n"
"\n"
"    color: rgb(131, 255, 241);\n"
"}")
        self.push_5.setObjectName("push_5")
        self.gridLayout_3.addWidget(self.push_5, 3, 1, 1, 1)
        self.push_mul = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_mul.sizePolicy().hasHeightForWidth())
        self.push_mul.setSizePolicy(sizePolicy)
        self.push_mul.setStyleSheet("QPushButton{\n"
"font: 75 28pt \"MS Shell Dlg 2\";\n"
"        color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 112);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              color: rgb(255, 152, 120);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 160, 160);\n"
"color: rgb(131, 255, 241);\n"
"}")
        self.push_mul.setObjectName("push_mul")
        self.gridLayout_3.addWidget(self.push_mul, 3, 3, 1, 1)
        self.push_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_2.sizePolicy().hasHeightForWidth())
        self.push_2.setSizePolicy(sizePolicy)
        self.push_2.setStyleSheet("QPushButton{\n"
"         font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"  background-color: rgb(194, 255, 230);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              \n"
"    color: rgb(50, 50, 50);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(135, 161, 166);\n"
"color: rgb(131, 255, 241);\n"
"}")
        self.push_2.setObjectName("push_2")
        self.gridLayout_3.addWidget(self.push_2, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 75 28pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 4)
        self.push_clear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_clear.sizePolicy().hasHeightForWidth())
        self.push_clear.setSizePolicy(sizePolicy)
        self.push_clear.setStyleSheet("QPushButton{\n"
"         \n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"  background-color: rgb(194, 255, 230);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              \n"
"    color: rgb(50, 50, 50);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(135, 161, 166);\n"
"\n"
"    color: rgb(131, 255, 241);\n"
"}")
        self.push_clear.setObjectName("push_clear")
        self.gridLayout_3.addWidget(self.push_clear, 1, 0, 1, 2)
        self.push_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_0.sizePolicy().hasHeightForWidth())
        self.push_0.setSizePolicy(sizePolicy)
        self.push_0.setStyleSheet("QPushButton{\n"
"         \n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"  background-color: rgb(194, 255, 230);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              \n"
"    color: rgb(50, 50, 50);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(135, 161, 166);\n"
"\n"
"    color: rgb(131, 255, 241);\n"
"}")
        self.push_0.setObjectName("push_0")
        self.gridLayout_3.addWidget(self.push_0, 5, 0, 1, 2)
        self.push_plus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_plus.sizePolicy().hasHeightForWidth())
        self.push_plus.setSizePolicy(sizePolicy)
        self.push_plus.setStyleSheet("QPushButton{\n"
"font: 75 28pt \"MS Shell Dlg 2\";\n"
"        color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 255, 112);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              color: rgb(255, 152, 120);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 160, 160);\n"
"color: rgb(131, 255, 241);\n"
"}")
        self.push_plus.setObjectName("push_plus")
        self.gridLayout_3.addWidget(self.push_plus, 1, 3, 1, 1)
        self.push_del = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_del.sizePolicy().hasHeightForWidth())
        self.push_del.setSizePolicy(sizePolicy)
        self.push_del.setStyleSheet("QPushButton{\n"
"         \n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"  background-color: rgb(194, 255, 230);\n"
"   \n"
"border-radius:29px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"              \n"
"    color: rgb(50, 50, 50);\n"
"    background-color: rgb(156, 200, 180);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(135, 161, 166);\n"
"\n"
"    color: rgb(131, 255, 241);\n"
"}")
        self.push_del.setObjectName("push_del")
        self.gridLayout_3.addWidget(self.push_del, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 373, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CALCULATOR"))
        self.push_8.setText(_translate("MainWindow", "8"))
        self.push_8.setShortcut(_translate("MainWindow", "8"))
        self.push_equ.setText(_translate("MainWindow", "="))
        self.push_equ.setShortcut(_translate("MainWindow", "="))
        self.push_6.setText(_translate("MainWindow", "6"))
        self.push_6.setShortcut(_translate("MainWindow", "6"))
        self.push_dot.setText(_translate("MainWindow", "."))
        self.push_dot.setShortcut(_translate("MainWindow", "."))
        self.push_div.setText(_translate("MainWindow", "/"))
        self.push_div.setShortcut(_translate("MainWindow", "/"))
        self.push_min.setText(_translate("MainWindow", "-"))
        self.push_min.setShortcut(_translate("MainWindow", "-"))
        self.push_4.setText(_translate("MainWindow", "4"))
        self.push_4.setShortcut(_translate("MainWindow", "4"))
        self.push_7.setText(_translate("MainWindow", "7"))
        self.push_7.setShortcut(_translate("MainWindow", "7"))
        self.push_9.setText(_translate("MainWindow", "9"))
        self.push_9.setShortcut(_translate("MainWindow", "9"))
        self.push_1.setText(_translate("MainWindow", "1"))
        self.push_1.setShortcut(_translate("MainWindow", "1"))
        self.push_3.setText(_translate("MainWindow", "3"))
        self.push_3.setShortcut(_translate("MainWindow", "3"))
        self.push_5.setText(_translate("MainWindow", "5"))
        self.push_5.setShortcut(_translate("MainWindow", "5"))
        self.push_mul.setText(_translate("MainWindow", "*"))
        self.push_mul.setShortcut(_translate("MainWindow", "*"))
        self.push_2.setText(_translate("MainWindow", "2"))
        self.push_2.setShortcut(_translate("MainWindow", "2"))
        self.label.setText(_translate("MainWindow", "0"))
        self.push_clear.setText(_translate("MainWindow", "Clear"))
        self.push_0.setText(_translate("MainWindow", "0"))
        self.push_0.setShortcut(_translate("MainWindow", "0"))
        self.push_plus.setText(_translate("MainWindow", "+"))
        self.push_plus.setShortcut(_translate("MainWindow", "+"))
        self.push_del.setText(_translate("MainWindow", "Del"))
        self.push_del.setShortcut(_translate("MainWindow", "Backspace"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
